# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82ca8c20b4f9714ff5d088d626d1f5aaaab543b23286368dbe1d354cdeba541c7b07cd6e0aae673039b2a67a8d7f559e3c360690cd2e5da3f2c5a7f67f54fd74

test:
  secret_key_base: d63b4e7f1c517677d90e7fd5a53200b96836c38c4d4ed947ad4f7ccb64c7bb8971db8b151ad8a2c1df5f92bb9e7c3bb859714a8b7aca930ba7c3103c4cebde41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
